baseURL = "https://babanin.net"
languageCode = "en-gb"
title = "Ivan Babanin"
theme = "archie"
copyright = "© Ivan Babanin"
publishDir = "public"

enableGitInfo = true

staticDir = ['static']

[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = 'trac'
tabWidth = 2

[params]
useCDN = true
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/babanin"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/0x_cafe_babe"

[[menu.main]]
name = "/posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "/tags"
url = "/tags"
weight = 3

#[[menu.main]]
#name = "/about"
#url = "/about"
#weight = 4

[services]
    [services.googleAnalytics]
        ID = 'G-DT0NK3W2WJ'